#!/usr/bin/env zsh

#    This a zsh prompt for a Solarized dark terminal colorscheme
#
#    Copyright (C) 2025 Anders Nygård
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

prompt_cozy_setup() {

	REPORTTIME=5
	TIMEFMT='%U user, %S kernel, %P cpu, %M maxmem(Mbyte), %X heap(kbyte), %D stack(kbyte), %K spacetot(kbyte), %*E totelapsed'

	# checkers
	#LEFT_MARKER=$'\u259E'
	#RIGHT_MARKER=$'\u259A'

	# quarter bar
	LEFT_MARKER=$'\u258C'
	RIGHT_MARKER=$'\u2590'

	zstyle -L ':cozy:marker' left > /dev/null && zstyle -s ':cozy:marker' left LEFT_MARKER
	zstyle -L ':cozy:marker' right > /dev/null && zstyle -s ':cozy:marker' right RIGHT_MARKER

	# designed for ghostty Builtin Solarized Dark

	COZY_BG='8'
	COZY_FG='14'
	COZY_FG_WARN='1'
	COZY_FG_ERR='3'
	COZY_FG_ACC1='6'
	COZY_FG_ACC2='2'

	zstyle -L ':cozy:background' regular > /dev/null && zstyle -s ':cozy:background' regular	COZY_BG
	zstyle -L ':cozy:foreground' regular > /dev/null && zstyle -s ':cozy:foreground' regular	COZY_FG
	zstyle -L ':cozy:foreground' warning > /dev/null && zstyle -s ':cozy:foreground' warning COZY_FG_WARN
	zstyle -L ':cozy:foreground' error > /dev/null && zstyle -s ':cozy:foreground' error COZY_FG_ERR
	zstyle -L ':cozy:foreground' primary_accent > /dev/null && zstyle -s ':cozy:foreground' primary_accent COZY_FG_ACC1
	zstyle -L ':cozy:foreground' secondary_accent > /dev/null && zstyle -s ':cozy:foreground' secondary_accent COZY_FG_ACC2

	COZY_VCS_BANNER=$'\ue725'
	zstyle -L ':cozy:vcs:char' banner > /dev/null && zstyle -s ':cozy:vcs:char' banner COZY_VCS_BANNER
	
	COZY_VCS_STAGED=s
	zstyle -L ':cozy:vcs:char' staged > /dev/null && zstyle -s ':cozy:vcs:char' staged COZY_VCS_STAGED

	COZY_VCS_UNSTAGED=u
	zstyle -L ':cozy:vcs:char' unstaged > /dev/null && zstyle -s ':cozy:vcs:char' unstaged COZY_VCS_UNSTAGED

	prompt_opts=(cr percent sp subst)
	autoload -Uz colors vcs_info
	colors

	#add-zsh-hook preexec prompt_cozy_preexec
	add-zsh-hook precmd prompt_cozy_precmd

	zstyle ':vcs_info:*' enable git 
	zstyle ':vcs_info:*' check-for-changes true 
	zstyle ':vcs_info:git:*' formats '%b %u%c %m'
	zstyle ':vcs_info:git:*' actionformats '%b %u%c %m %F{${COZY_FG_ACC2}}%a%f'
	zstyle ':vcs_info:*' stagedstr $COZY_VCS_STAGED
	zstyle ':vcs_info:*' unstagedstr $COZY_VCS_UNSTAGED

	ZLE_RPROMPT_INDENT=0
	PS1='${LEFT_MARKER} %(#.#.$)%E %E '
	PS2='${LEFT_MARKER} %_>%E '
	RPS1='%~ %n%F{${COZY_FG_ACC1}}@%f%m ${RIGHT_MARKER}'
	RPS2='${RIGHT_MARKER}'
}
	
prompt_cozy_precmd() {

	EXITCODE="$?"
	vcs_info
        EC="%F{${COZY_FG_ACC1}}?%f"
	if [ "$EXITCODE" -eq 0 ] ; then
		EC="${EC}${EXITCODE}" 
	else
		EC="${EC}%F{${COZY_FG_ERR}}${EXITCODE}%f" 
	fi
	VCS_INFO=''
	if [ -n "$vcs_info_msg_0_" ] ; then
		VCS_INFO="%F{${COZY_FG_ACC1}}${COZY_VCS_BANNER}%f${(MS)vcs_info_msg_0_##[[:graph:]]*[[:graph:]]} "
	fi
	print -Pn '%K{${COZY_BG}}%F{${COZY_FG}}${LEFT_MARKER} 20%D %T ${EC} %(1j.%F{${COZY_FG_ACC1}}j%f%j.) ${VCS_INFO} %E'
	print "\e[$((COLUMNS))G${RIGHT_MARKER}"
}

prompt_cozy_preexec() {
	print -P '%k%E'
}

prompt_cozy_setup "$@"

